### ISSUE TITLE
Support libxkbcommon 0.4.3

### ISSUE THREAD

**Issue by b-r-u** [francesca64/xkbcommon-dl#1]
Debian 8.10 still uses libxkbcommon 0.4.3. Accessing an `XKBCOMMON_HANDLE` results in a panic because the symbols concerning compose tables and compose states (from libxkbcommon 0.5) are missing:

https://github.com/francesca64/xkbcommon-dl/blob/9d35ac837821dcdc4f937242f83bae7460a99146/src/lib.rs#L261-L276

It would be nice if this library could handle different versions at runtime. There is a similar issue for x11-rs (https://github.com/Daggerbot/x11-rs/issues/35). They chose to add different structs for different versions, but it would also be possible to detect the version in a build script and to enable features accordingly.

**Comment by francesca64** [comment]
Thanks for catching this! 

This is unfortunate news though, since I'm not sure how to compensate for this missing functionality in winit's keyboard handling.

**Comment by b-r-u** [comment]
Thanks for merging!
The winit branch doesn't panic anymore and I'll do some research on the dead key situation without xkbcommon (A lot of searching brought me here https://stackoverflow.com/a/18288346 for a start).
